# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a25953c7f98db721752d6272124fdc3a75a6ffe412acfc2aa659512e9319f88be9a1b511cca8121127fbaa795f01cd5f902534a728bffb093f92b2f3df1275c

test:
  secret_key_base: be7b41fbf102ffece440f8c74615edfd2f3139dfbd20022a5a884e70369eaabd3136f87cfef9012636903fe918f7d033509db6686e33da22215eabf1ac4f79bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
